name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_COMPANY_EMAIL: ${{ secrets.COMPANY_EMAIL }}
      NEXT_PUBLIC_SMTP_HOST: ${{ secrets.NEXT_PUBLIC_SMTP_HOST }}
      NEXT_PUBLIC_SMTP_PORT: ${{ secrets.NEXT_PUBLIC_SMTP_PORT }}
      NEXT_PUBLIC_SMTP_LOGIN: ${{ secrets.NEXT_PUBLIC_SMTP_LOGIN }}
      NEXT_PUBLIC_SMTP_PASSWORD: ${{ secrets.NEXT_PUBLIC_SMTP_PASSWORD }}
      NEXT_PUBLIC_COMPANY_PHONE: ${{ secrets.NEXT_PUBLIC_COMPANY_PHONE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm install -g vercel

      - name: Pull Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
